/**
 * connection_requests — one row per pair of users (enforced by the
 * uq_connection_requests_user_pair index on the generated pair columns).
 * The row's status moves through the lifecycle; business rules live in
 * services/connectionService.js.
 */
const BaseModel = require('./BaseModel');
const { getDb } = require('../config/database');

const STATUS = Object.freeze({
  PENDING: 'pending',
  ACCEPTED: 'accepted',
  REJECTED: 'rejected',
  CANCELLED: 'cancelled',
  DISCONNECTED: 'disconnected',
});

// Columns written by the application (pair_* columns are generated by the database).
const COLUMNS = ['request_id', 'sender_id', 'receiver_id', 'status', 'responded_at', 'created_at', 'updated_at'];

class ConnectionRequestModel extends BaseModel {
  constructor() {
    super({ table: 'connection_requests', primaryKey: 'request_id' });
  }

  /** The single row linking two users (either direction), or undefined. */
  findBetween(user1Id, user2Id, trx) {
    return this.query(trx)
      .select(COLUMNS)
      .where((sub) => {
        sub.where({ sender_id: user1Id, receiver_id: user2Id }).orWhere({ sender_id: user2Id, receiver_id: user1Id });
      })
      .first();
  }

  findById(requestId, trx) {
    return this.query(trx).select(COLUMNS).where({ request_id: requestId }).first();
  }

  async create(senderId, receiverId, trx) {
    const now = new Date();
    return this.insertAndGetId(
      { sender_id: senderId, receiver_id: receiverId, status: STATUS.PENDING, created_at: now, updated_at: now },
      trx
    );
  }

  /**
   * Re-opens an ended relationship (still in `fromStatus`) as a new pending
   * request. The direction is reset to the new sender and created_at to now.
   * Returns false when a concurrent request changed the row first.
   */
  async reopen(requestId, fromStatus, senderId, receiverId, trx) {
    const now = new Date();
    const updated = await this.query(trx).where({ request_id: requestId, status: fromStatus }).update({
      sender_id: senderId,
      receiver_id: receiverId,
      status: STATUS.PENDING,
      responded_at: null,
      created_at: now,
      updated_at: now,
    });
    return updated === 1;
  }

  /**
   * Moves a row from `fromStatus` to `toStatus`. The status condition makes
   * the transition atomic: returns false when the row was no longer in
   * `fromStatus` (e.g. a concurrent request already changed it).
   */
  async transition(requestId, fromStatus, toStatus, trx, { responded = false } = {}) {
    const now = new Date();
    const changes = { status: toStatus, updated_at: now };
    if (responded) changes.responded_at = now;
    const updated = await this.query(trx).where({ request_id: requestId, status: fromStatus }).update(changes);
    return updated === 1;
  }

  /**
   * Rows for a user joined with the OTHER user's profile, restricted to
   * active accounts with a profile and to pairs where neither user has
   * blocked the other.
   *
   * @param {number} userId
   * @param {'sent'|'received'|'connected'} role
   * @param {string[]} statuses
   */
  listWithCounterpart(userId, role, statuses, trx) {
    const db = trx || getDb();
    const q = this.query(trx);

    if (role === 'sent') {
      q.join('profiles', 'profiles.user_id', 'connection_requests.receiver_id').where('connection_requests.sender_id', userId);
    } else if (role === 'received') {
      q.join('profiles', 'profiles.user_id', 'connection_requests.sender_id').where('connection_requests.receiver_id', userId);
    } else {
      q.join('profiles', (on) => {
        on.on(
          'profiles.user_id',
          db.raw('CASE WHEN ?? = ? THEN ?? ELSE ?? END', [
            'connection_requests.sender_id',
            userId,
            'connection_requests.receiver_id',
            'connection_requests.sender_id',
          ])
        );
      }).where((sub) => sub.where('connection_requests.sender_id', userId).orWhere('connection_requests.receiver_id', userId));
    }

    return q
      .join('users', 'users.user_id', 'profiles.user_id')
      .where('users.status', 'active')
      .whereIn('connection_requests.status', statuses)
      .whereNotExists(function blockedEitherWay() {
        this.select(db.raw('1'))
          .from('blocks')
          .where((b) => b.where('blocks.blocker_id', userId).andWhere('blocks.blocked_id', db.ref('profiles.user_id')))
          .orWhere((b) => b.where('blocks.blocked_id', userId).andWhere('blocks.blocker_id', db.ref('profiles.user_id')));
      })
      .select(
        ...COLUMNS.map((c) => `connection_requests.${c}`),
        'profiles.user_id as other_user_id',
        'profiles.name',
        'profiles.date_of_birth',
        'profiles.city',
        'profiles.state',
        'profiles.country',
        'profiles.profile_photo_url'
      );
  }
}

module.exports = new ConnectionRequestModel();
module.exports.STATUS = STATUS;
