/**
 * Local-disk storage: files live under UPLOADS_DIR and are served by app.js
 * at /media/<key>. Suitable for development and single-server deployments.
 *
 * Keys are generated by the server (never taken from the client) and are
 * checked against a strict pattern, so no path traversal is possible.
 */
const fs = require('fs/promises');
const path = require('path');
const config = require('../../config/environment');

const URL_PREFIX = '/media/';
const KEY_PATTERN = /^[a-z0-9-]+\/[a-f0-9-]{36}\.[a-z0-9]{3,4}$/;

function resolveKey(key) {
  if (!KEY_PATTERN.test(key)) throw new Error('Invalid storage key');
  const root = config.media.uploadsDir;
  const file = path.resolve(root, key);
  if (!file.startsWith(root + path.sep)) throw new Error('Invalid storage key');
  return file;
}

async function put(key, buffer) {
  const file = resolveKey(key);
  await fs.mkdir(path.dirname(file), { recursive: true });
  await fs.writeFile(file, buffer, { flag: 'wx' }); // never overwrite
  return { key, url: `${URL_PREFIX}${key}` };
}

async function remove(key) {
  try {
    await fs.unlink(resolveKey(key));
  } catch (err) {
    if (err.code !== 'ENOENT') throw err;
  }
}

/** Storage key for a URL produced by put(), or null if it is not ours. */
function keyFromUrl(url) {
  if (typeof url !== 'string' || !url.startsWith(URL_PREFIX)) return null;
  const key = url.slice(URL_PREFIX.length);
  return KEY_PATTERN.test(key) ? key : null;
}

module.exports = { name: 'local', put, remove, keyFromUrl, URL_PREFIX };
